=== lutharsanen/DVU-Master-Thesis/src/submissions/movie/DeepVideoUnderstandingResults.dtd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- DTD for results from one Deep Video Understanding movie -->
<!-- DeepVideoUnderstandingResults contains the Deep Video Understanding Results for a single test set movie -->
<!ELEMENT DeepVideoUnderstandingResults (DeepVideoUnderstandingRunResult)>
<!-- movie - the name of the movie this submisssion answers questions on
-->
<!ATTLIST DeepVideoUnderstandingResults movie   CDATA     #REQUIRED>
<!-- DTD for a results of a single Deep Video Understanding run -->
<!-- A Deep Video Understanding run result contains the Deep Video Understanding Results for
a single system (variant) run against all the topics
-->

<!ELEMENT DeepVideoUnderstandingRunResult (DeepVideoUnderstandingTopicResult+)>

<!-- pid - short participant id

     priority - evaluation priority (1,2,...) If not all runs can be
             judged, then judging will begin with the run with priority
             1 and so on.

     desc - verbal description of the characteristics of this run,
             how it differs in approach, resources, etc from others
             runs.


-->
<!ATTLIST DeepVideoUnderstandingRunResult pid   CDATA     #REQUIRED 
                            	priority   (1|2|3|4|5|6|7|8) #REQUIRED
                           	desc   CDATA     #REQUIRED>


<!-- A Deep Video Understanding topic result contains the query results for
a single topic.
-->
<!ELEMENT DeepVideoUnderstandingTopicResult (item*)>


<!-- question - which question number is this answering (1,2, or 3)


     id - which part of the question are we answering - (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18)
     
     
     path - for question 1 only - which path number is this listing for
  
-->

<!ATTLIST DeepVideoUnderstandingTopicResult   question (1|2|3|4|5) #REQUIRED
                            id (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18) #REQUIRED
                            path CDATA  #IMPLIED>
                            
                            

<!ELEMENT item     EMPTY >

<!-- order - provide the ordering of the answer to the question - applies to question 3 only

     subject - where the subject of the question - the actual answer - should be provided - applies to question 3 only
     
     confidence - the confidence rating for this answer - applies to question 3 only
     
     type - applies to question 3 only - the type being questioned about (relation, entity etc.)
     
     answer - provide the answer to the question - question 3 only

     scene - Provide the scene number to show evidence of this
     relation - question 3 only
     
     source - the source entity being referred to - question 1 only
     
     target - the target entity being referred to - question 1 only
     
     relation - the relation from source to target - question 1 only

--> 
<!ATTLIST item   type CDATA	#IMPLIED
               order CDATA	#IMPLIED
               subject CDATA	#IMPLIED
               confidence CDATA	#IMPLIED
               relation CDATA #IMPLIED
               source CDATA	#IMPLIED
               type CDATA	#IMPLIED
               answer CDATA #IMPLIED
               scene CDATA   #IMPLIED
               target CDATA	#IMPLIED>

=== lutharsanen/DVU-Master-Thesis/src/submissions/movie/movie_little_rock.xml
<?xml version="1.0" ?>
<!DOCTYPE DeepVideoUnderstandingResults SYSTEM "DeepVideoUnderstandingResults.dtd">
<DeepVideoUnderstandingResults movie="little_rock">
	<DeepVideoUnderstandingRunResult desc="A Multi-Stream Approach for Video Understanding" pid="UZH" priority="1">
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="1">
			<item source="francisco" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="brody"/>
			<item source="brody" relation="friend of" target="atsuko"/>
			<item source="atsuko" relation="friend of" target="cory"/>
			<item source="cory" relation="friend of" target="garbo"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="2">
			<item source="francisco" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="brody"/>
			<item source="brody" relation="friend of" target="atsuko"/>
			<item source="atsuko" relation="friend of" target="cory"/>
			<item source="cory" relation="lives at" target="house2"/>
			<item source="house2" relation="residence of" target="garbo"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="3">
			<item source="francisco" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="brody"/>
			<item source="brody" relation="friend of" target="atsuko"/>
			<item source="atsuko" relation="friend of" target="cory"/>
			<item source="cory" relation="lives at" target="shop"/>
			<item source="shop" relation="residence of" target="garbo"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="4">
			<item source="francisco" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="brody"/>
			<item source="brody" relation="friend of" target="garbo"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="5">
			<item source="francisco" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="cory"/>
			<item source="cory" relation="friend of" target="atsuko"/>
			<item source="atsuko" relation="friend of" target="brody"/>
			<item source="brody" relation="friend of" target="garbo"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="6">
			<item source="francisco" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="cory"/>
			<item source="cory" relation="friend of" target="garbo"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="7">
			<item source="francisco" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="cory"/>
			<item source="cory" relation="lives at" target="house2"/>
			<item source="house2" relation="residence of" target="garbo"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="8">
			<item source="francisco" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="cory"/>
			<item source="cory" relation="lives at" target="shop"/>
			<item source="shop" relation="residence of" target="garbo"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="9">
			<item source="francisco" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="garbo"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="2" path="1">
			<item source="jordan" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="sean"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3" path="1">
			<item source="brody" relation="friend of" target="atsuko"/>
			<item source="atsuko" relation="friend of" target="cory"/>
			<item source="cory" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="marques"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3" path="2">
			<item source="brody" relation="friend of" target="atsuko"/>
			<item source="atsuko" relation="friend of" target="cory"/>
			<item source="cory" relation="friend of" target="garbo"/>
			<item source="garbo" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="marques"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3" path="3">
			<item source="brody" relation="friend of" target="atsuko"/>
			<item source="atsuko" relation="friend of" target="cory"/>
			<item source="cory" relation="lives at" target="house2"/>
			<item source="house2" relation="residence of" target="garbo"/>
			<item source="garbo" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="marques"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3" path="4">
			<item source="brody" relation="friend of" target="atsuko"/>
			<item source="atsuko" relation="friend of" target="cory"/>
			<item source="cory" relation="lives at" target="shop"/>
			<item source="shop" relation="residence of" target="garbo"/>
			<item source="garbo" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="marques"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3" path="5">
			<item source="brody" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="marques"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3" path="6">
			<item source="brody" relation="friend of" target="garbo"/>
			<item source="garbo" relation="friend of" target="cory"/>
			<item source="cory" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="marques"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3" path="7">
			<item source="brody" relation="friend of" target="garbo"/>
			<item source="garbo" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="marques"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3" path="8">
			<item source="brody" relation="friend of" target="garbo"/>
			<item source="garbo" relation="lives at" target="house2"/>
			<item source="house2" relation="residence of" target="cory"/>
			<item source="cory" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="marques"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3" path="9">
			<item source="brody" relation="friend of" target="garbo"/>
			<item source="garbo" relation="lives at" target="shop"/>
			<item source="shop" relation="residence of" target="cory"/>
			<item source="cory" relation="friend of" target="dad"/>
			<item source="dad" relation="friend of" target="marques"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="1">
			<item order="1" subject="none" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="2">
			<item order="1" subject="none" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="3">
			<item order="1" subject="atsuko" confidence="33"/>
			<item order="2" subject="dad" confidence="33"/>
			<item order="3" subject="garbo" confidence="33"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="4">
			<item order="1" subject="none" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="1">
			<item type="Relation" answer="None"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="2">
			<item type="Relation" answer="None"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="3">
			<item type="Relation" answer="None"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="4">
			<item type="Entity" answer="unknown"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="5">
			<item type="Relation" answer="None"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="6">
			<item type="Integer" answer="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="7">
			<item type="Relation" answer="unknown"/>
		</DeepVideoUnderstandingTopicResult>
	</DeepVideoUnderstandingRunResult>
</DeepVideoUnderstandingResults>

=== lutharsanen/DVU-Master-Thesis/src/submissions/movie/movie_ChainedforLife.xml
<?xml version="1.0" ?>
<!DOCTYPE DeepVideoUnderstandingResults SYSTEM "DeepVideoUnderstandingResults.dtd">
<DeepVideoUnderstandingResults movie="ChainedforLife">
	<DeepVideoUnderstandingRunResult desc="A Multi-Stream Approach for Video Understanding" pid="UZH" priority="1">
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="1">
			<item source="michelle" relation="engaged with by" target="herr_director"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="2" path="1">
			<item source="max" relation="is not liked by" target="herr_director"/>
			<item source="herr_director" relation="engages with" target="mabel"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="2" path="2">
			<item source="max" relation="is not liked by" target="herr_director"/>
			<item source="herr_director" relation="friend of" target="rosenthal"/>
			<item source="rosenthal" relation="friend of" target="mabel"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="2" path="3">
			<item source="max" relation="friend of" target="mabel"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="1">
			<item order="1" subject="none" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="2">
			<item order="1" subject="none" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="3">
			<item order="1" subject="none" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="1">
			<item type="Relation" answer="None"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="2">
			<item type="Relation" answer="None"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="3">
			<item type="Relation" answer="unknown"/>
		</DeepVideoUnderstandingTopicResult>
	</DeepVideoUnderstandingRunResult>
</DeepVideoUnderstandingResults>

=== lutharsanen/DVU-Master-Thesis/src/submissions/movie/movie_losing_ground.xml
<?xml version="1.0" ?>
<!DOCTYPE DeepVideoUnderstandingResults SYSTEM "DeepVideoUnderstandingResults.dtd">
<DeepVideoUnderstandingResults movie="losing_ground">
	<DeepVideoUnderstandingRunResult desc="A Multi-Stream Approach for Video Understanding" pid="UZH" priority="1">
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="1">
			<item source="duke" relation="child of" target="carlos"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="2">
			<item source="duke" relation="friend of" target="sara"/>
			<item source="sara" relation="friend of" target="carlos"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="3">
			<item source="duke" relation="friend of" target="sara"/>
			<item source="sara" relation="friend of" target="victor"/>
			<item source="victor" relation="friend of" target="carlos"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3" path="1">
			<item source="gypsy" relation="friend of" target="carlos"/>
			<item source="carlos" relation="parent of" target="duke"/>
			<item source="duke" relation="friend of" target="sara"/>
			<item source="sara" relation="friend of" target="victor"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3" path="2">
			<item source="gypsy" relation="friend of" target="carlos"/>
			<item source="carlos" relation="friend of" target="sara"/>
			<item source="sara" relation="friend of" target="victor"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3" path="3">
			<item source="gypsy" relation="friend of" target="carlos"/>
			<item source="carlos" relation="friend of" target="victor"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="1">
			<item order="1" subject="carlos" confidence="50"/>
			<item order="2" subject="sara" confidence="50"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="2">
			<item order="1" subject="none" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="3">
			<item order="1" subject="none" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="4">
			<item order="1" subject="duke" confidence="100"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="1">
			<item type="Relation" answer="unknown"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="2"/>
		<DeepVideoUnderstandingTopicResult question="3" id="3">
			<item type="Integer" answer="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="4">
			<item type="Relation" answer="None"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="5">
			<item type="Relation" answer="unknown"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="6">
			<item type="Relation" answer="lives at"/>
		</DeepVideoUnderstandingTopicResult>
	</DeepVideoUnderstandingRunResult>
</DeepVideoUnderstandingResults>

=== lutharsanen/DVU-Master-Thesis/src/submissions/movie/movie_like_me.xml
<?xml version="1.0" ?>
<!DOCTYPE DeepVideoUnderstandingResults SYSTEM "DeepVideoUnderstandingResults.dtd">
<DeepVideoUnderstandingResults movie="like_me">
	<DeepVideoUnderstandingRunResult desc="A Multi-Stream Approach for Video Understanding" pid="UZH" priority="1">
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="1">
			<item source="burt" relation="friend of" target="gas_station_clerk"/>
			<item source="gas_station_clerk" relation="acquaintance of" target="kiya"/>
			<item source="kiya" relation="friend of" target="marshall"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="2">
			<item source="burt" relation="friend of" target="gas_station_clerk"/>
			<item source="gas_station_clerk" relation="acquaintance of" target="marshall"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="3">
			<item source="burt" relation="friend of" target="gas_station_clerk"/>
			<item source="gas_station_clerk" relation="is treating" target="diner"/>
			<item source="diner" relation="residence of" target="kiya"/>
			<item source="kiya" relation="friend of" target="marshall"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="4">
			<item source="burt" relation="engages with" target="kiya"/>
			<item source="kiya" relation="acquaintance of" target="gas_station_clerk"/>
			<item source="gas_station_clerk" relation="acquaintance of" target="marshall"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="5">
			<item source="burt" relation="engages with" target="kiya"/>
			<item source="kiya" relation="friend of" target="marshall"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="6">
			<item source="burt" relation="engages with" target="kiya"/>
			<item source="kiya" relation="lives at" target="diner"/>
			<item source="diner" relation="patient at" target="gas_station_clerk"/>
			<item source="gas_station_clerk" relation="acquaintance of" target="marshall"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="1" path="7">
			<item source="burt" relation="friend of" target="marshall"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="1">
			<item order="1" subject="none" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="1"/>
		<DeepVideoUnderstandingTopicResult question="3" id="2">
			<item type="Relation" answer="unknown"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="3">
			<item type="Relation" answer="knows of"/>
		</DeepVideoUnderstandingTopicResult>
	</DeepVideoUnderstandingRunResult>
</DeepVideoUnderstandingResults>
