=== lutharsanen/DVU-Master-Thesis/src/submissions/scene/DeepVideoUnderstandingSceneResults.dtd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- DTD for scene level results from one Deep Video Understanding movie -->

<!-- DeepVideoUnderstandingSceneResults contains the Deep Video Understanding Results for a single test movie -->

<!ELEMENT DeepVideoUnderstandingSceneResults (DeepVideoUnderstandingRunResult)>

<!-- movie - the name of the movie this submisssion answers questions on


-->

<!ATTLIST DeepVideoUnderstandingSceneResults movie   CDATA     #REQUIRED>

<!-- DTD for a results of a single Deep Video Understanding scene-level run -->


<!-- A Deep Video Understanding run result contains the Deep Video Understanding Results for
a single system (variant) run against all the scene-level topics
-->

<!ELEMENT DeepVideoUnderstandingRunResult (DeepVideoUnderstandingTopicResult+)>

<!-- pid - short participant id

     priority - evaluation priority (1,2,...) If not all runs can be
             judged, then judging will begin with the run with priority
             1 and so on.

     desc - verbal description of the characteristics of this run,
             how it differs in approach, resources, etc from others
             runs.


-->
<!ATTLIST DeepVideoUnderstandingRunResult pid   CDATA     #REQUIRED 
                            	priority   (1|2|3|4|5|6|7|8) #REQUIRED
                           	desc   CDATA     #REQUIRED>


<!-- A Deep Video Understanding topic result contains the query results for
a single topic.
-->
<!ELEMENT DeepVideoUnderstandingTopicResult (item*)>


<!-- question - which question number is this answering (1,2, or 3)


     id - which part of the question are we answering - (1|2|3|4|5|6|7|8|9|10)
     
     
     path - for question 3 only - which path number is this listing for
  
-->

<!ATTLIST DeepVideoUnderstandingTopicResult   question (1|2|3|4|5|6) #REQUIRED
                            id (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20) #REQUIRED
                            path CDATA  #IMPLIED>
                            
                            

<!ELEMENT item     EMPTY >

<!-- order - provide the ordering of the answer to the question - applies to question 1, and 2 only

     subject - where the subject of the question - the actual answer - should be provided - applies to question 2 only
     
     confidence - the confidence rating for this answer - applies to question 1, and 2 only
     
     type - applies to questions 3, 4, 5, and 6 only - the type being questioned about (relation, entity etc.)
     
     scene - applies to questions 2, 3, and 4 only - the scene being asked about
     
     answer - provide the answer to the question - question 3, 4, 5,
     and 6 only

     start_time - Provide the start time of a clip (in seconds) within
     the specified scene where evidence of this interation exists - Questions 3 & 4 only

     end_time - Provide the end time of a clip (in seconds) within the
     specified scene where evidence of this interation exists - Questions 3 & 4 only


--> 
<!ATTLIST item   type CDATA	#IMPLIED
               order CDATA	#IMPLIED
               subject CDATA	#IMPLIED
               confidence CDATA	#IMPLIED
               scene CDATA	#IMPLIED
               answer CDATA #IMPLIED
               start_time CDATA #IMPLIED
               end_time CDATA  #IMPLIED>

=== lutharsanen/DVU-Master-Thesis/src/submissions/scene/like_me_scene.xml
<?xml version="1.0" ?>
<!DOCTYPE DeepVideoUnderstandingSceneResults SYSTEM "DeepVideoUnderstandingSceneResults.dtd">
<DeepVideoUnderstandingSceneResults movie="like_me">
	<DeepVideoUnderstandingRunResult desc="A Multi-Stream Approach for Video Understanding" pid="UZH" priority="1">
		<DeepVideoUnderstandingTopicResult question="1" id="1">
			<item order="1" scene="like_me-15" confidence="26.506024096385538"/>
			<item order="2" scene="like_me-13" confidence="15.903614457831324"/>
			<item order="3" scene="like_me-13" confidence="15.903614457831324"/>
			<item order="4" scene="like_me-2" confidence="13.253012048192769"/>
			<item order="5" scene="like_me-2" confidence="13.253012048192769"/>
			<item order="6" scene="like_me-20" confidence="7.951807228915662"/>
			<item order="7" scene="like_me-22" confidence="7.2289156626506035"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="2">
			<item order="1" scene="like_me-1" confidence="10.894941634241242"/>
			<item order="2" scene="like_me-1" confidence="10.894941634241242"/>
			<item order="3" scene="like_me-1" confidence="10.894941634241242"/>
			<item order="4" scene="like_me-13" confidence="8.171206225680933"/>
			<item order="5" scene="like_me-13" confidence="8.171206225680933"/>
			<item order="6" scene="like_me-13" confidence="8.171206225680933"/>
			<item order="7" scene="like_me-13" confidence="8.171206225680933"/>
			<item order="8" scene="like_me-13" confidence="8.171206225680933"/>
			<item order="9" scene="like_me-2" confidence="6.536964980544748"/>
			<item order="10" scene="like_me-2" confidence="6.536964980544748"/>
			<item order="11" scene="like_me-15" confidence="5.447470817120621"/>
			<item order="12" scene="like_me-7" confidence="4.6692607003891045"/>
			<item order="13" scene="like_me-22" confidence="3.268482490272374"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3">
			<item order="1" scene="like_me-4" confidence="42.85714285714286"/>
			<item order="2" scene="like_me-3" confidence="35.71428571428571"/>
			<item order="3" scene="like_me-22" confidence="21.42857142857143"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="4">
			<item order="1" scene="like_me-13" confidence="20.797227036395142"/>
			<item order="2" scene="like_me-13" confidence="20.797227036395142"/>
			<item order="3" scene="like_me-2" confidence="15.597920277296362"/>
			<item order="4" scene="like_me-2" confidence="15.597920277296362"/>
			<item order="5" scene="like_me-15" confidence="12.478336221837088"/>
			<item order="6" scene="like_me-20" confidence="7.798960138648181"/>
			<item order="7" scene="like_me-22" confidence="6.932409012131716"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="1">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="2">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="3">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="4">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="1">
			<item type="Interaction" answer="talks to"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="2">
			<item type="Interaction" answer="asks"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="3"/>
		<DeepVideoUnderstandingTopicResult question="3" id="4"/>
		<DeepVideoUnderstandingTopicResult question="4" id="1">
			<item type="Interaction" answer="gives to"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="4" id="2">
			<item type="Interaction" answer="gives to"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="4" id="3"/>
		<DeepVideoUnderstandingTopicResult question="4" id="4"/>
	</DeepVideoUnderstandingRunResult>
</DeepVideoUnderstandingSceneResults>

=== lutharsanen/DVU-Master-Thesis/src/submissions/scene/little_rock_scene.xml
<?xml version="1.0" ?>
<!DOCTYPE DeepVideoUnderstandingSceneResults SYSTEM "DeepVideoUnderstandingSceneResults.dtd">
<DeepVideoUnderstandingSceneResults movie="little_rock">
	<DeepVideoUnderstandingRunResult desc="A Multi-Stream Approach for Video Understanding" pid="UZH" priority="1">
		<DeepVideoUnderstandingTopicResult question="1" id="1">
			<item order="1" scene="little_rock-14" confidence="10.737943056362584"/>
			<item order="2" scene="little_rock-10" confidence="10.226612434631031"/>
			<item order="3" scene="little_rock-8" confidence="9.761766414875076"/>
			<item order="4" scene="little_rock-19" confidence="7.954031893601914"/>
			<item order="5" scene="little_rock-25" confidence="7.158628704241724"/>
			<item order="6" scene="little_rock-6" confidence="6.507844276583386"/>
			<item order="7" scene="little_rock-15" confidence="5.965523920201435"/>
			<item order="8" scene="little_rock-15" confidence="5.965523920201435"/>
			<item order="9" scene="little_rock-11" confidence="5.1133062173155155"/>
			<item order="10" scene="little_rock-11" confidence="5.1133062173155155"/>
			<item order="11" scene="little_rock-11" confidence="5.1133062173155155"/>
			<item order="12" scene="little_rock-17" confidence="4.474142940151077"/>
			<item order="13" scene="little_rock-17" confidence="4.474142940151077"/>
			<item order="14" scene="little_rock-17" confidence="4.474142940151077"/>
			<item order="15" scene="little_rock-27" confidence="3.977015946800957"/>
			<item order="16" scene="little_rock-21" confidence="2.9827619601007176"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="2">
			<item order="1" scene="little_rock-19" confidence="12.912061038833997"/>
			<item order="2" scene="little_rock-15" confidence="8.608040692556"/>
			<item order="3" scene="little_rock-15" confidence="8.608040692556"/>
			<item order="4" scene="little_rock-11" confidence="7.747236623300399"/>
			<item order="5" scene="little_rock-11" confidence="7.747236623300399"/>
			<item order="6" scene="little_rock-11" confidence="7.747236623300399"/>
			<item order="7" scene="little_rock-10" confidence="7.042942384818546"/>
			<item order="8" scene="little_rock-10" confidence="7.042942384818546"/>
			<item order="9" scene="little_rock-10" confidence="7.042942384818546"/>
			<item order="10" scene="little_rock-27" confidence="6.4560305194169985"/>
			<item order="11" scene="little_rock-14" confidence="5.1648244155336"/>
			<item order="12" scene="little_rock-14" confidence="5.1648244155336"/>
			<item order="13" scene="little_rock-8" confidence="4.84202288956275"/>
			<item order="14" scene="little_rock-4" confidence="3.8736183116501994"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3">
			<item order="1" scene="little_rock-14" confidence="9.977352537422645"/>
			<item order="2" scene="little_rock-8" confidence="9.209863880697826"/>
			<item order="3" scene="little_rock-10" confidence="8.86875781104235"/>
			<item order="4" scene="little_rock-19" confidence="7.256256390852833"/>
			<item order="5" scene="little_rock-4" confidence="7.042837085239515"/>
			<item order="6" scene="little_rock-6" confidence="6.1399092537985505"/>
			<item order="7" scene="little_rock-25" confidence="5.701344307098654"/>
			<item order="8" scene="little_rock-15" confidence="4.988676268711322"/>
			<item order="9" scene="little_rock-15" confidence="4.988676268711322"/>
			<item order="10" scene="little_rock-11" confidence="4.434378905521175"/>
			<item order="11" scene="little_rock-11" confidence="4.434378905521175"/>
			<item order="12" scene="little_rock-11" confidence="4.434378905521175"/>
			<item order="13" scene="little_rock-11" confidence="4.434378905521175"/>
			<item order="14" scene="little_rock-17" confidence="3.990941014969058"/>
			<item order="15" scene="little_rock-17" confidence="3.990941014969058"/>
			<item order="16" scene="little_rock-27" confidence="3.6281281954264166"/>
			<item order="17" scene="little_rock-27" confidence="3.6281281954264166"/>
			<item order="18" scene="little_rock-21" confidence="2.850672153549327"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="4">
			<item order="1" scene="little_rock-3" confidence="9.747409560393585"/>
			<item order="2" scene="little_rock-10" confidence="8.861281418539624"/>
			<item order="3" scene="little_rock-4" confidence="7.69532333715283"/>
			<item order="4" scene="little_rock-14" confidence="6.498273040262391"/>
			<item order="5" scene="little_rock-14" confidence="6.498273040262391"/>
			<item order="6" scene="little_rock-8" confidence="6.092130975245991"/>
			<item order="7" scene="little_rock-12" confidence="5.415227533551992"/>
			<item order="8" scene="little_rock-12" confidence="5.415227533551992"/>
			<item order="9" scene="little_rock-12" confidence="5.415227533551992"/>
			<item order="10" scene="little_rock-12" confidence="5.415227533551992"/>
			<item order="11" scene="little_rock-15" confidence="4.8737047801967925"/>
			<item order="12" scene="little_rock-15" confidence="4.8737047801967925"/>
			<item order="13" scene="little_rock-23" confidence="4.430640709269812"/>
			<item order="14" scene="little_rock-23" confidence="4.430640709269812"/>
			<item order="15" scene="little_rock-36" confidence="4.061420650163993"/>
			<item order="16" scene="little_rock-28" confidence="3.749003677074456"/>
			<item order="17" scene="little_rock-19" confidence="3.481217700140566"/>
			<item order="18" scene="little_rock-6" confidence="3.0460654876229953"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="1">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="2">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="3">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="4">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="1">
			<item type="Interaction" answer="talks to"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="2">
			<item type="Interaction" answer="talks to"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="3"/>
		<DeepVideoUnderstandingTopicResult question="3" id="4"/>
		<DeepVideoUnderstandingTopicResult question="4" id="1">
			<item type="Interaction" answer="holds in arms"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="4" id="2"/>
		<DeepVideoUnderstandingTopicResult question="4" id="3"/>
		<DeepVideoUnderstandingTopicResult question="4" id="4"/>
	</DeepVideoUnderstandingRunResult>
</DeepVideoUnderstandingSceneResults>

=== lutharsanen/DVU-Master-Thesis/src/submissions/scene/ChainedforLife_scene.xml
<?xml version="1.0" ?>
<!DOCTYPE DeepVideoUnderstandingSceneResults SYSTEM "DeepVideoUnderstandingSceneResults.dtd">
<DeepVideoUnderstandingSceneResults movie="ChainedforLife">
	<DeepVideoUnderstandingRunResult desc="A Multi-Stream Approach for Video Understanding" pid="UZH" priority="1">
		<DeepVideoUnderstandingTopicResult question="1" id="1">
			<item order="1" scene="ChainedforLife-10" confidence="26.494565217391308"/>
			<item order="2" scene="ChainedforLife-10" confidence="26.494565217391308"/>
			<item order="3" scene="ChainedforLife-25" confidence="21.195652173913047"/>
			<item order="4" scene="ChainedforLife-16" confidence="17.663043478260867"/>
			<item order="5" scene="ChainedforLife-20" confidence="8.15217391304348"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="2">
			<item order="1" scene="ChainedforLife-10" confidence="47.44525547445255"/>
			<item order="2" scene="ChainedforLife-25" confidence="37.95620437956204"/>
			<item order="3" scene="ChainedforLife-16" confidence="14.5985401459854"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3">
			<item order="1" scene="ChainedforLife-20" confidence="100.0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="4">
			<item order="1" scene="ChainedforLife-20" confidence="100.0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="1">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="2">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="3">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="4">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="1">
			<item type="Interaction" answer="talks to"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="2"/>
		<DeepVideoUnderstandingTopicResult question="3" id="3"/>
		<DeepVideoUnderstandingTopicResult question="3" id="4"/>
		<DeepVideoUnderstandingTopicResult question="4" id="1"/>
		<DeepVideoUnderstandingTopicResult question="4" id="2"/>
		<DeepVideoUnderstandingTopicResult question="4" id="3"/>
	</DeepVideoUnderstandingRunResult>
</DeepVideoUnderstandingSceneResults>

=== lutharsanen/DVU-Master-Thesis/src/submissions/scene/Liberty_Kid_scene.xml
<?xml version="1.0" ?>
<!DOCTYPE DeepVideoUnderstandingSceneResults SYSTEM "DeepVideoUnderstandingSceneResults.dtd">
<DeepVideoUnderstandingSceneResults movie="Liberty_Kid">
	<DeepVideoUnderstandingRunResult desc="A Multi-Stream Approach for Video Understanding" pid="UZH" priority="1">
		<DeepVideoUnderstandingTopicResult question="1" id="1">
			<item order="1" scene="None" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="2">
			<item order="1" scene="Liberty_Kid-19" confidence="9.015777610818933"/>
			<item order="2" scene="Liberty_Kid-1" confidence="6.761833208114202"/>
			<item order="3" scene="Liberty_Kid-1" confidence="6.761833208114202"/>
			<item order="4" scene="Liberty_Kid-1" confidence="6.761833208114202"/>
			<item order="5" scene="Liberty_Kid-1" confidence="6.761833208114202"/>
			<item order="6" scene="Liberty_Kid-1" confidence="6.761833208114202"/>
			<item order="7" scene="Liberty_Kid-1" confidence="6.761833208114202"/>
			<item order="8" scene="Liberty_Kid-1" confidence="6.761833208114202"/>
			<item order="9" scene="Liberty_Kid-22" confidence="5.409466566491361"/>
			<item order="10" scene="Liberty_Kid-22" confidence="5.409466566491361"/>
			<item order="11" scene="Liberty_Kid-22" confidence="5.409466566491361"/>
			<item order="12" scene="Liberty_Kid-25" confidence="4.507888805409467"/>
			<item order="13" scene="Liberty_Kid-13" confidence="3.380916604057101"/>
			<item order="14" scene="Liberty_Kid-13" confidence="3.380916604057101"/>
			<item order="15" scene="Liberty_Kid-13" confidence="3.380916604057101"/>
			<item order="16" scene="Liberty_Kid-13" confidence="3.380916604057101"/>
			<item order="17" scene="Liberty_Kid-13" confidence="3.380916604057101"/>
			<item order="18" scene="Liberty_Kid-27" confidence="3.0052592036063115"/>
			<item order="19" scene="Liberty_Kid-27" confidence="3.0052592036063115"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3">
			<item order="1" scene="Liberty_Kid-40" confidence="56.25"/>
			<item order="2" scene="Liberty_Kid-8" confidence="43.75"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="4">
			<item order="1" scene="None" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="1">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="2">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="3">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="4">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="1"/>
		<DeepVideoUnderstandingTopicResult question="3" id="2"/>
		<DeepVideoUnderstandingTopicResult question="3" id="3"/>
		<DeepVideoUnderstandingTopicResult question="3" id="4"/>
		<DeepVideoUnderstandingTopicResult question="4" id="1"/>
		<DeepVideoUnderstandingTopicResult question="4" id="2"/>
		<DeepVideoUnderstandingTopicResult question="4" id="3"/>
		<DeepVideoUnderstandingTopicResult question="4" id="4"/>
	</DeepVideoUnderstandingRunResult>
</DeepVideoUnderstandingSceneResults>

=== lutharsanen/DVU-Master-Thesis/src/submissions/scene/Calloused_Hands_scene.xml
<?xml version="1.0" ?>
<!DOCTYPE DeepVideoUnderstandingSceneResults SYSTEM "DeepVideoUnderstandingSceneResults.dtd">
<DeepVideoUnderstandingSceneResults movie="Calloused_Hands">
	<DeepVideoUnderstandingRunResult desc="A Multi-Stream Approach for Video Understanding" pid="UZH" priority="1">
		<DeepVideoUnderstandingTopicResult question="1" id="1">
			<item order="1" scene="Calloused_Hands-25" confidence="6.690028671551448"/>
			<item order="2" scene="Calloused_Hands-31" confidence="5.017521503663587"/>
			<item order="3" scene="Calloused_Hands-31" confidence="5.017521503663587"/>
			<item order="4" scene="Calloused_Hands-31" confidence="5.017521503663587"/>
			<item order="5" scene="Calloused_Hands-31" confidence="5.017521503663587"/>
			<item order="6" scene="Calloused_Hands-31" confidence="5.017521503663587"/>
			<item order="7" scene="Calloused_Hands-31" confidence="5.017521503663587"/>
			<item order="8" scene="Calloused_Hands-31" confidence="5.017521503663587"/>
			<item order="9" scene="Calloused_Hands-10" confidence="4.014017202930869"/>
			<item order="10" scene="Calloused_Hands-10" confidence="4.014017202930869"/>
			<item order="11" scene="Calloused_Hands-10" confidence="4.014017202930869"/>
			<item order="12" scene="Calloused_Hands-10" confidence="4.014017202930869"/>
			<item order="13" scene="Calloused_Hands-10" confidence="4.014017202930869"/>
			<item order="14" scene="Calloused_Hands-10" confidence="4.014017202930869"/>
			<item order="15" scene="Calloused_Hands-11" confidence="3.345014335775724"/>
			<item order="16" scene="Calloused_Hands-11" confidence="3.345014335775724"/>
			<item order="17" scene="Calloused_Hands-11" confidence="3.345014335775724"/>
			<item order="18" scene="Calloused_Hands-11" confidence="3.345014335775724"/>
			<item order="19" scene="Calloused_Hands-1" confidence="2.867155144950621"/>
			<item order="20" scene="Calloused_Hands-1" confidence="2.867155144950621"/>
			<item order="21" scene="Calloused_Hands-1" confidence="2.867155144950621"/>
			<item order="22" scene="Calloused_Hands-1" confidence="2.867155144950621"/>
			<item order="23" scene="Calloused_Hands-36" confidence="2.5087607518317934"/>
			<item order="24" scene="Calloused_Hands-36" confidence="2.5087607518317934"/>
			<item order="25" scene="Calloused_Hands-21" confidence="2.2300095571838163"/>
			<item order="26" scene="Calloused_Hands-29" confidence="2.0070086014654347"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="2">
			<item order="1" scene="Calloused_Hands-38" confidence="7.330482590103847"/>
			<item order="2" scene="Calloused_Hands-1" confidence="5.701486458969658"/>
			<item order="3" scene="Calloused_Hands-1" confidence="5.701486458969658"/>
			<item order="4" scene="Calloused_Hands-1" confidence="5.701486458969658"/>
			<item order="5" scene="Calloused_Hands-31" confidence="4.276114844227244"/>
			<item order="6" scene="Calloused_Hands-31" confidence="4.276114844227244"/>
			<item order="7" scene="Calloused_Hands-31" confidence="4.276114844227244"/>
			<item order="8" scene="Calloused_Hands-31" confidence="4.276114844227244"/>
			<item order="9" scene="Calloused_Hands-31" confidence="4.276114844227244"/>
			<item order="10" scene="Calloused_Hands-31" confidence="4.276114844227244"/>
			<item order="11" scene="Calloused_Hands-29" confidence="3.800990972646439"/>
			<item order="12" scene="Calloused_Hands-10" confidence="3.4208918753817956"/>
			<item order="13" scene="Calloused_Hands-10" confidence="3.4208918753817956"/>
			<item order="14" scene="Calloused_Hands-10" confidence="3.4208918753817956"/>
			<item order="15" scene="Calloused_Hands-10" confidence="3.4208918753817956"/>
			<item order="16" scene="Calloused_Hands-10" confidence="3.4208918753817956"/>
			<item order="17" scene="Calloused_Hands-10" confidence="3.4208918753817956"/>
			<item order="18" scene="Calloused_Hands-10" confidence="3.4208918753817956"/>
			<item order="19" scene="Calloused_Hands-11" confidence="2.850743229484829"/>
			<item order="20" scene="Calloused_Hands-11" confidence="2.850743229484829"/>
			<item order="21" scene="Calloused_Hands-11" confidence="2.850743229484829"/>
			<item order="22" scene="Calloused_Hands-11" confidence="2.850743229484829"/>
			<item order="23" scene="Calloused_Hands-27" confidence="2.443494196701282"/>
			<item order="24" scene="Calloused_Hands-30" confidence="2.138057422113622"/>
			<item order="25" scene="Calloused_Hands-30" confidence="2.138057422113622"/>
			<item order="26" scene="Calloused_Hands-30" confidence="2.138057422113622"/>
			<item order="27" scene="Calloused_Hands-21" confidence="1.9004954863232195"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="3">
			<item order="1" scene="Calloused_Hands-14" confidence="15.67651632970451"/>
			<item order="2" scene="Calloused_Hands-14" confidence="15.67651632970451"/>
			<item order="3" scene="Calloused_Hands-1" confidence="11.197511664074648"/>
			<item order="4" scene="Calloused_Hands-1" confidence="11.197511664074648"/>
			<item order="5" scene="Calloused_Hands-1" confidence="11.197511664074648"/>
			<item order="6" scene="Calloused_Hands-30" confidence="9.797822706065318"/>
			<item order="7" scene="Calloused_Hands-38" confidence="8.709175738724726"/>
			<item order="8" scene="Calloused_Hands-38" confidence="8.709175738724726"/>
			<item order="9" scene="Calloused_Hands-29" confidence="7.838258164852255"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="1" id="4">
			<item order="1" scene="Calloused_Hands-14" confidence="15.67651632970451"/>
			<item order="2" scene="Calloused_Hands-14" confidence="15.67651632970451"/>
			<item order="3" scene="Calloused_Hands-1" confidence="11.197511664074648"/>
			<item order="4" scene="Calloused_Hands-1" confidence="11.197511664074648"/>
			<item order="5" scene="Calloused_Hands-1" confidence="11.197511664074648"/>
			<item order="6" scene="Calloused_Hands-30" confidence="9.797822706065318"/>
			<item order="7" scene="Calloused_Hands-38" confidence="8.709175738724726"/>
			<item order="8" scene="Calloused_Hands-38" confidence="8.709175738724726"/>
			<item order="9" scene="Calloused_Hands-29" confidence="7.838258164852255"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="1">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="2">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="3">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="2" id="4">
			<item order="1" subject="Person:unknown" confidence="0"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="1"/>
		<DeepVideoUnderstandingTopicResult question="3" id="2"/>
		<DeepVideoUnderstandingTopicResult question="3" id="3">
			<item type="Interaction" answer="asks"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="3" id="4"/>
		<DeepVideoUnderstandingTopicResult question="4" id="1"/>
		<DeepVideoUnderstandingTopicResult question="4" id="2">
			<item type="Interaction" answer="talks to"/>
		</DeepVideoUnderstandingTopicResult>
		<DeepVideoUnderstandingTopicResult question="4" id="3"/>
		<DeepVideoUnderstandingTopicResult question="4" id="4">
			<item type="Interaction" answer="asks"/>
		</DeepVideoUnderstandingTopicResult>
	</DeepVideoUnderstandingRunResult>
</DeepVideoUnderstandingSceneResults>
